version: "3.1"

services:
  postgres:
    image: postgres:latest
    container_name: app_db
    restart: always
    environment:
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_DB: $PGDATABASE
    networks:
      - app_network
    volumes:
      - ./database:/var/lib/postgresql
    ports:
    - 5432:5432

  registration:
    container_name: registration_app
    build:
      context: ./server/registration
    networks:
      - app_network
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0:8000"
    depends_on:
      - postgres

  sign_in:
    container_name: sign_in_app
    build:
      context: ./server/signin
    networks:
      - app_network
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0:8001"
    depends_on:
      - postgres

  nginx:
    build: ./web
    ports:
      - 80:80
    depends_on:
      - sign_in
      - registration
    links:
      - registration
      - sign_in
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
