# Generated by Django 3.1.7 on 2021-03-16 12:11

from django.db import migrations, models
import django.db.models.deletion
import index_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('template', models.FileField(max_length=128, upload_to='templates/blocks/', validators=[index_app.validators.validate_file_extension])),
            ],
            options={
                'verbose_name': 'Блоки',
                'verbose_name_plural': 'Блоки',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('template', models.FileField(max_length=128, upload_to='templates/data/', validators=[index_app.validators.validate_file_extension])),
                ('data', models.TextField(default='{}')),
            ],
            options={
                'verbose_name': 'Данные',
                'verbose_name_plural': 'данные',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('template', models.FileField(max_length=128, upload_to='templates/elements/', validators=[index_app.validators.validate_file_extension])),
                ('depends_in', models.ManyToManyField(to='index_app.Data')),
            ],
            options={
                'verbose_name': 'Элементы',
                'verbose_name_plural': 'Элементы',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(default='Title', max_length=64, unique=True)),
                ('description', models.CharField(default='', max_length=128, unique=True)),
                ('template', models.FileField(max_length=128, upload_to='templates/pages/', validators=[index_app.validators.validate_file_extension])),
                ('blocks', models.ManyToManyField(to='index_app.Block')),
            ],
            options={
                'verbose_name': 'Страницы',
                'verbose_name_plural': 'страницы',
            },
        ),
        migrations.CreateModel(
            name='BlockAdmin',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='index_app.block')),
            ],
            bases=('index_app.block',),
        ),
        migrations.CreateModel(
            name='DataAdmin',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='index_app.data')),
            ],
            bases=('index_app.data',),
        ),
        migrations.CreateModel(
            name='ElementAdmin',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='index_app.element')),
            ],
            bases=('index_app.element',),
        ),
        migrations.CreateModel(
            name='PageAdmin',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='index_app.page')),
            ],
            bases=('index_app.page',),
        ),
        migrations.AddField(
            model_name='block',
            name='depends_on',
            field=models.ManyToManyField(to='index_app.Element'),
        ),
    ]
